### ISSUE TITLE
Picture Naming Convention

### ISSUE THREAD

**Issue by GeraldDC2512** [GeraldDC2512/Telkom#4]
Name_Recentpic.png

**Comment by SH-chopper** [comment]
![personality test 3](https://user-images.githubusercontent.com/62311803/83097737-2d3e3900-a0ec-11ea-8e78-ff27e5a659cf.jpg)
![personality test 2](https://user-images.githubusercontent.com/62311803/83097739-2e6f6600-a0ec-11ea-8cf8-fd9256462374.jpg)
![Personality test 1](https://user-images.githubusercontent.com/62311803/83097743-2f07fc80-a0ec-11ea-8a76-e1b926e5db5f.jpg)

**Comment by SH-chopper** [comment]
![20200518_161255](https://user-images.githubusercontent.com/62311803/83145787-b24f3f80-a138-11ea-9a5a-400cc487e13a.jpg)
